name: Deno

# 触发条件
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  # 自动化测试
  test:
    # 运行的机器宿主环境
    runs-on: ubuntu-latest

    # 运行的步骤
    steps:
      #拉取代码
      - name: Setup repo
        uses: actions/checkout@v3

      # 初始化deno到运行环境中
      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.2
        with:
          deno-version: v1.x
      # 开始测试
      - name: Run tests
        run: deno test test/* test/*/* -A --unstable
